### ISSUE TITLE
Cant get it to run

### ISSUE THREAD

**Issue by Blotz** [nvfp/Handwritten-Character-Recognition#1]
I've tried with python 3.8 and 3.9 in linux
All other versions wont install the specified versions

steps to reproduce!
```bash
tar xzf 1.1.0.tar.gz
cd Handwritten-Character-Recognition-1.1.0/
python3 -m venv venv
. ./venv/bin/activate
pip install -r requirements.txt
python3 __main__.py
```

error for Python 3.8.16
```bash
Traceback (most recent call last):
  File "__main__.py", line 14, in <module>
    from mykit.app.button import Button
  File "/home/user/dox/git/Handwritten-Character-Recognition-1.1.0/venv/lib/python3.8/site-packages/mykit/app/button.py", line 6, in <module>
    class Button:
  File "/home/user/dox/git/Handwritten-Character-Recognition-1.1.0/venv/lib/python3.8/site-packages/mykit/app/button.py", line 13, in Button
    buttons: dict[str, 'Button'] = {}
TypeError: 'type' object is not subscriptable
```
error for Python 3.9.16
```bash
Traceback (most recent call last):
  File "/home/user/dox/git/Handwritten-Character-Recognition-1.1.0/__main__.py", line 14, in <module>
    from mykit.app.button import Button
  File "/home/user/dox/git/Handwritten-Character-Recognition-1.1.0/venv/lib/python3.9/site-packages/mykit/app/button.py", line 6, in <module>
    class Button:
  File "/home/user/dox/git/Handwritten-Character-Recognition-1.1.0/venv/lib/python3.9/site-packages/mykit/app/button.py", line 20, in Button
    fn: _typing.Callable[[], None] | None = None,
TypeError: unsupported operand type(s) for |: '_CallableGenericAlias' and 'NoneType'
```

**Comment by nvfp** [comment]
Hi, thanks for letting me know. Sorry I forgot to mention that it should be run on python310.

I will close the issue once I finish the next version, the next version should be able to run on at least 3.8.
